### ISSUE TITLE
Pointer lock not working

### ISSUE THREAD

**Issue by thorsteinsson** [toji/webgl-quake3#1]
I am using Chrome 18 on a mac and the pointer lock is not working. I am running the game on localhost and I have enabled the pointer lock functionality in about:flags. I also tested chrome canary with same result.

I tried updating to version 0.5 of the game shim and then my keyboard stopped working (W, A, S, D) and still no pointer lock.

When I start the game the following error appears in the console (both locally and on your server).

Uncaught Line: 71, Uncaught Error: INVALID_STATE_ERR: DOM Exception 11   ------  q3bsp.js:55
Uncaught Error: INVALID_STATE_ERR: DOM Exception 11     -------  /q3bsp/js/q3bsp_worker.js:71

However the pointer lock described on this webpage works.
http://updates.html5rocks.com/2012/02/Pointer-Lock-API-Brings-FPS-Games-to-the-Browser

**Comment by crossonrose** [comment]
I beleive you.
