### ISSUE TITLE
Incompatible BSP version.

### ISSUE THREAD

**Issue by tvalentius** [toji/webgl-quake3#12]
Hi there,

i tried to run this code base locally but it says "Incompatible BSP version.".

Is there anything i should add before running the code?

**Comment by toji** [comment]
The github repo does not contain the necessary media to run the demo. You would have to extract that from a copy of Quake 3 Arena yourself and do a few minor conversions. I have some brief notes about it [here](https://github.com/toji/webgl-quake3/tree/master/demo_baseq3).

**Comment by tvalentius** [comment]
ah i see, thanks for the help @toji
